### ISSUE TITLE
Feature request; I want blacklist policy

### ISSUE THREAD

**Issue by odg0318** [kassisol/hbm#11]
Hello.

As I know, your plugin support restrictions to by default deny all commands and allow available commands called whitelist.
My use case needs blacklist which by default allows all and deny some commands.

Please tell me how to do above if there is already the feature.

Thanks! 

Best regards

**Comment by juliengk** [comment]
Hello,

There is no possibility to achieve what you want which is to allow all then blacklist commands.

But let me think about it.

Thanks

**Comment by odg0318** [comment]
@juliengk In my opinion, you can utilize plugin's initial settings to implement blacklist policy.
Otherwise, what do you think of adding allow/deny to policy columns to distinguish?
Plugin policy could be designed like iptables rule.

Thanks.

**Comment by odg0318** [comment]
Closed
