### ISSUE TITLE
Feature Request; Default config setting when executing hbm

### ISSUE THREAD

**Issue by odg0318** [kassisol/hbm#12]
Hello.

When hbm is executed, initial config is set in code; `authorization=false`. which makes hbm disabled.
It seems like that there is no hbm server daemon option about that.

Thanks

**Comment by odg0318** [comment]
I edited `hbm.service` file and temporarily resolved this issue.
```
[Unit]
Description=Harbormaster Plugin
Before=docker.service
After=network.target hbm.socket
Requires=hbm.socket docker.service

[Service]
Type=simple
TimeoutStartSec=0
Restart=always
RestartSec=10s
ExecStartPre=-/usr/sbin/hbm init
ExecStartPre=-/usr/sbin/hbm config set authorization true
ExecStart=/usr/sbin/hbm server

[Install]
WantedBy=multi-user.target
```

**Comment by juliengk** [comment]
Hello,

Could you make a PR with your change please?

Thanks

**Comment by juliengk** [comment]
I have made a change to avoid setting config values to default after running hbm init multiple times. Here is the commit https://github.com/kassisol/hbm/commit/a5966e5dfb9a6cd8ef8b2cf9b2594bb262ba20f1

**Comment by odg0318** [comment]
It's nice. Additionally, what do you think of using config file such as hbm.yml or hbm. json?

**Comment by juliengk** [comment]
what advantages can you think to have a config file?

**Comment by odg0318** [comment]
@juliengk I will deploy docker with hbm to multiple servers.
To enable authorization,  additional operation must be executed as time as new server is added.
I think that config file makes configuration management simpler.

Otherwise, environment is also nice way.

**Comment by juliengk** [comment]
you can use puppet or another cm to deploy and configure it. My idea is to have a central API.

**Comment by odg0318** [comment]
Ok, Thanks. I will close this issue.
