### ISSUE TITLE
panic with docker-compose

### ISSUE THREAD

**Issue by odg0318** [kassisol/hbm#15]
Hello.

I am using `hbm` master version.
When I tested with `hbm` and `docker-compose`, a panic occurred on 38 lines  `pkg/cmdbuilder/cmdbuilder.go`.
And error message is below.
```
time="2018-01-20T04:42:05-05:00" level=warning msg="Recovered panic: json: cannot unmarshal array into Go value of type map[string]bool"
```
To unmarshal filters, `map[string]map[string]bool` is supposed as a struct.

```go
func (c *Config) AddFilters() {
        if len(c.Params) > 0 {
                if _, ok := c.Params["filters"]; ok {
                        var v map[string]map[string]bool

                        err := json.Unmarshal([]byte(c.Params["filters"][0]), &v)
                        if err != nil {
                                panic(err)
                        }

                        for k, val := range v {
                                for ka := range val {
                                        c.Add(fmt.Sprintf("--filter \"%s=%s\"", k, ka))
                                }
                        }
                }
        }
}
```

I slightly changed  the code to check `c.Params["filters"][0]` and the result is below.
```
[{"label": ["com.docker.compose.project=dockerfluentd", "com.docker.compose.oneoff=False"]}]
```
`dockerfluentd` looks like my project name I tested.
And when `docker-compose up` is executed, at the beginning of steps, docker-compose searches container list with above label filters.

I don't know what is supposed to unmarshal using this code.
I check and examine your plugin to harden my job security.
I have an attention to progressively contribute this plugin.

Thanks

**Comment by odg0318** [comment]
In my opinion, filters' value is not fixed to `bool` type.
https://docs.docker.com/engine/reference/commandline/ps/#filtering

**Comment by odg0318** [comment]
It seems like that this code is only for logging.. right?
It regenerates docker command line from docker api request.

And filters type is `map[string][]string` such as `{"status": ["paused"]}` in the document(https://docs.docker.com/engine/api/v1.35/#tag/Container) .

I tested and checked actual data through docker cli but it seems different from data in document.

**Comment by juliengk** [comment]
maybe in api documentation but in the code it's otherwise https://github.com/moby/moby/blob/master/api/types/filters/parse.go#L17

**Comment by juliengk** [comment]
can you provide your docker compose file?

**Comment by odg0318** [comment]
@juliengk 

```bash
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
```bash
$ docker-compose version
docker-compose version 1.17.0, build ac53b73
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```
And to make a panic, no complex docker-compose file is needed.
```
version: "3"                                                                                                                                                                                                                                                                                                                                                                                                  services:                                                                                                                                                                                                alpine:
    image: alpine
```

**Comment by juliengk** [comment]
Hi,

I have made change to package cmdbuilder to habdle compose filters format. https://github.com/kassisol/hbm/commit/4dfbeefe51c9b1a80a2c7471c0e7759a65306a7c

Let me know if that works for you now

Thanks

**Comment by odg0318** [comment]
@juliengk It works fine with docker-compose.
What do you think of using regex to check docker cli or docker-compose?
I am taking about `strings.Contains(c.Params["filters"][0], "[")`.

**Comment by juliengk** [comment]
sure! what is your suggestion?

**Comment by odg0318** [comment]
Check PR #17.  Closed
