### ISSUE TITLE
Policy for multiple private registries

### ISSUE THREAD

**Issue by odg0318** [kassisol/hbm#18]
Hello.

Multiple private registries are used for my project.
But now only one registry could be allowed via configuration.
It seems like that there is no way to set policy value as array.

If you note me that, I could implement it instead of you.

Thanks.

**Comment by juliengk** [comment]
I'm not sure to understand.

Can't you create multiple resources with your private registries? Then add those resources to a collection and to finish configure the collection in the policy.

**Comment by odg0318** [comment]
I didn't know to set multiple resources.
But your comment helps what I wan to do.
Thanks!
