### ISSUE TITLE
harbormaster.io DNS expired

### ISSUE THREAD

**Issue by per-bohlin** [kassisol/hbm#34]
Hi,

The DNS for harbormaster.io no longer points to the documentation website. The DNS has expired (Dec 15, 2018).

**Comment by juliengk** [comment]
Hi,

Yes, I haven't renewed the domain but you can find documentation in the repo folder [docs](https://github.com/kassisol/hbm/tree/master/docs).

Let me know if you have a question.

Thanks

**Comment by per-bohlin** [comment]
The online documentation was more convenient since the index pages doesn't work properly from the docs folder. I however completely understand if you don't want to pay for the domain indefinitely.

Thank you for the plugin, it has been of great help.
