### ISSUE TITLE
Resourcetype volumedriver missing?

### ISSUE THREAD

**Issue by nenne70** [kassisol/hbm#39]
The documentation states that 

`hbm resource add --type volumedriver --value ....`

But when executing command

`[root@eselnvlx2448 ~]# hbm resource add --type volumedriver --value local localdriver
FATA[0000] The Resource Driver: volumedriver is not supported. Supported drivers are action,capability,config,device,dns,image,logdriver,logopt,plugin,port,registry,volume 
`

Has volumedriver been removed intentionally or is it a misstake or has the usage changed?

**Comment by juliengk** [comment]
the import of that resource never been included by omission. #41
